# Generated by Django 4.0.5 on 2022-06-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=10, default=99.99, max_digits=15)),
            ],
        ),
    ]
